//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspcrud.Models
{
    using System;
    using System.Collections.Generic;
  using System.ComponentModel;
  using System.ComponentModel.DataAnnotations;

  public partial class member
    {
        public member()
        {
            this.articles = new HashSet<article>();
        }
    
        public long id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage ="This field ismandatory")]
        public string uname { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]

    [Required(ErrorMessage = "This field ismandatory")]
    public string pass { get; set; }
        public System.DateTime regdate { get; set; }
        public byte[] images { get; set; }
    
        public virtual ICollection<article> articles { get; set; }

    public String LoginErrorMessage { get; set; }
  }
}
